name: Auto Build neMAX

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 */2 * *'

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Russian Locale
        run: |
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale LANG=ru_RU.UTF-8

      - name: Download Target APK from RuStore
        run: |
          RESPONSE=$(curl -s -X POST "https://backapi.rustore.ru/applicationData/v2/download-link" \
            -H "Content-Type: application/json" \
            -d '{
              "appId": 2063618637,
              "firstInstall": true,
              "mobileServices": [],
              "screenDensity": 0,
              "sdkVersion": 26,
              "signatureFingerprint": null,
              "supportedAbis": ["x86_64", "arm64-v8a", "x86", "armeabi-v7a", "armeabi"],
              "supportedLocales": ["ru_RU"],
              "withoutSplits": true
            }')
          
          DOWNLOAD_URL=$(echo "$RESPONSE" | jq -r '.body.downloadUrls[0].url')
          
          if [ "$DOWNLOAD_URL" == "null" ] || [ -z "$DOWNLOAD_URL" ]; then
            echo "Ошибка: Не удалось получить ссылку. Ответ API: $RESPONSE"
            exit 1
          fi
          
          echo "Ссылка получена, скачиваю..."
          curl -L "$DOWNLOAD_URL" -o target.apk
          
      - name: Calculate Hash
        id: calc_hash
        run: |
          FILE_HASH=$(sha256sum target.apk | awk '{print $1}')
          echo "APK_HASH=$FILE_HASH" >> $GITHUB_ENV
          echo "Hash is $FILE_HASH"

      - name: Check Cache (Prevent Duplicate Builds)
        id: check_cache
        uses: actions/cache@v4
        with:
          path: target.apk
          key: apk-processed-${{ env.APK_HASH }}
      
      - name: Stop if already processed
        if: steps.check_cache.outputs.cache-hit == 'true' && github.event_name != 'workflow_dispatch'
        run: |
          echo "Этот APK уже был собран. Отмена."
          exit 0


      - name: Setup Java
        if: success()
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Tools (Zipalign, ImageMagick)
        if: success()
        run: |
          sudo apt-get update && sudo apt-get install -y zipalign imagemagick
          chmod +x apktool.jar
          
      - name: Decode Keystore
        if: success()
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      - name: Decompile APK
        if: success()
        run: |
          java -jar apktool.jar d target.apk -o base_src

      - name: Apply Common Mods
        if: success()
        working-directory: base_src
        run: |
          # Permissions
          sed -i '/android.permission.REQUEST_INSTALL_PACKAGES/d' AndroidManifest.xml
          sed -i '/android.permission.ACCESS_FINE_LOCATION/d' AndroidManifest.xml
          sed -i '/android.permission.BLUETOOTH_CONNECT/d' AndroidManifest.xml
          sed -i '/android.permission.RECEIVE_BOOT_COMPLETED/d' AndroidManifest.xml
          sed -i '/android.permission.ACCESS_COARSE_LOCATION/d' AndroidManifest.xml

          # Trackers
          grep -rl "tracker-api.vk-analytics.ru" . | xargs sed -i 's/tracker-api.vk-analytics.ru/0.0.0.0/g'
          grep -rl "sdk-api.apptracer.ru" . | xargs sed -i 's/sdk-api.apptracer.ru/0.0.0.0/g'

      - name: Create Build Variants
        if: success()
        run: |
          cp -r base_src src_orig
          cp -r base_src src_nemax

      
      - name: Mod Original Branding Version
        if: success()
        working-directory: src_orig/res/values
        run: |
          sed -i 's|<string name="oneme_faq_link">https://help.max.ru</string>|<string name="oneme_faq_link">https://telegra.ph/CHto-takoe-neMAX-12-08</string>|g' strings.xml
          sed -i 's|<string name="chat_list_toolbar_title">Чаты</string>|<string name="chat_list_toolbar_title">Чаты \| Мод от @nemax_mod</string>|g' strings.xml
          sed -i 's|<string name="about_app_settings_version">Версия приложения</string>|<string name="about_app_settings_version">Версия MAX. Мод от @nemax_mod</string>|g' strings.xml

      - name: Build & Sign Original Branding
        if: success()
        run: |
          java -jar apktool.jar b src_orig -o uns_orig.apk
          zipalign -p -f -v 4 uns_orig.apk aligned_orig.apk
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks release.keystore --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} --out neMAX-Original-Branding.apk aligned_orig.apk


      - name: Mod neMAX Full Version
        if: success()
        run: |
          sed -i 's|<string name="oneme_app_name">MAX</string>|<string name="oneme_app_name">neMAX</string>|g' src_nemax/res/values/strings.xml
          sed -i 's|<string name="oneme_faq_link">https://help.max.ru</string>|<string name="oneme_faq_link">https://telegra.ph/CHto-takoe-neMAX-12-08</string>|g' src_nemax/res/values/strings.xml
          sed -i 's|<string name="chat_list_toolbar_title">Чаты</string>|<string name="chat_list_toolbar_title">Чаты \| Мод от @nemax_mod</string>|g' src_nemax/res/values/strings.xml
          sed -i 's|<string name="about_app_settings_version">Версия приложения</string>|<string name="about_app_settings_version">Версия MAX. Мод от @nemax_mod</string>|g' src_nemax/res/values/strings.xml

          echo "Resizing icons..."
          SOURCE_ICON="ic_launcher_background.webp"
          
          resize_icon() {
            local folder=$1
            local size=$2
            convert "$SOURCE_ICON" -resize "${size}x${size}!" "src_nemax/res/$folder/ic_launcher_background.webp"
          }

          resize_icon "mipmap-mdpi"    "108"
          resize_icon "mipmap-hdpi"    "162"
          resize_icon "mipmap-xhdpi"   "216"
          resize_icon "mipmap-xxhdpi"  "324"
          resize_icon "mipmap-xxxhdpi" "432"

          cat <<EOF > src_nemax/res/drawable/ic_launcher_foreground.xml
          <?xml version="1.0" encoding="utf-8"?>
          <vector android:height="108.0dip" android:width="108.0dip" android:viewportWidth="373.0" android:viewportHeight="371.0"
            xmlns:android="http://schemas.android.com/apk/res/android">
              <group android:scaleX="0.47055554" android:scaleY="0.46803248" android:translateX="98.74139" android:translateY="98.67998">
                  <path android:fillColor="#ffffffff" android:pathData="M190.06,369.48C153.52,369.48 136.55,364.13 107.11,342.72C88.38,366.8 29.43,385.53 26.84,353.42C26.84,329.37 21.44,309.1 15.49,286.78C8.2,259.45 0.09,229.04 0.09,184.85C0.09,79.48 86.56,0.23 189.09,0.23C291.62,0.23 372.01,83.35 372.01,185.88C372.01,288.41 289.06,369.48 190.06,369.48ZM191.55,91.33C141.66,88.71 102.72,123.31 94.14,177.47C87.03,222.31 99.63,276.96 110.41,279.71C115.5,281.01 128.52,270.48 136.54,262.45C149.75,271.01 164.9,277.63 181.74,278.52C232.96,281.2 278.36,241.14 281.04,189.94C283.72,138.75 242.77,94.01 191.55,91.33Z" android:fillType="evenOdd" />
              </group>
          </vector>
          EOF

      - name: Build & Sign neMAX Full
        if: success()
        run: |
          java -jar apktool.jar b src_nemax -o uns_nemax.apk
          zipalign -p -f -v 4 uns_nemax.apk aligned_nemax.apk
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks release.keystore --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} --out neMAX-Full.apk aligned_nemax.apk


      - name: Generate Release Info
        if: success()
        id: release_info
        run: |
          export LC_TIME=ru_RU.UTF-8
          DATE_STR=$(date "+%d %B %Y года")
          echo "RELEASE_DATE=$DATE_STR" >> $GITHUB_ENV

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.APK_HASH }}
          name: Обновление до базы MAX на момент ${{ env.RELEASE_DATE }}
          files: |
            neMAX-Original-Branding.apk
            neMAX-Full.apk
          body: |
            ### 🤖 Автоматический релиз neMAX
            Базовая версия приложения обновлена до актуальной версии MAX на момент ${{ env.RELEASE_DATE }}.
            **Hash базы (SHA256):** `${{ env.APK_HASH }}`
            
            ---
            
            ### Инструкция по установке
            1. Перед установкой **neMAX** настоятельно рекомендуется удалить оригинальное приложение MAX.
            2. Обновление поверх старой версии neMAX может пройти успешно, но если возникают ошибки — удалите старую версию и установите новую начисто.
            
            ### Что изменено (Changelog)
            Это автоматическая версия, никаких дополнительных улучшений (improvements), кроме базового мода:
            *   Удалены трекеры и аналитика (заглушены на 0.0.0.0).
            *   Вырезаны лишние Permissions (доступ к местоположению, установке пакетов и др.).
            *   В полной версии изменены иконки и название.
            
            ### ⚖️ ToS и Отказ от ответственности
            > Скачивая, дыша, смотря или делая хоть что-то с APK neMAX, ты соглашаешься с [ToS проекта neMAX](https://tos.nemax-mod.ru).
            
            *Все заявления автора и описание мода стоит рассматривать только через призму ToS проекта neMAX и здравого смысла.*
            
            *Данная сборка сформирована автоматически GitHub Actions.*
